### ISSUE TITLE
SVN not a supported material

### ISSUE THREAD

**Issue by hanej** [SpringerSBM/gomatic#11]
It appears SVN is not a supported material.  While trying to clone a template, it threw an exception as soon as it got to an SVN material in the XML.

Traceback (most recent call last):
  File "gocli.py", line 777, in <module>
    args.clonetemplate[0], args.clonetemplate[1])
  File "gocli.py", line 516, in clone_template
    self.configurator.save_updated_config()
  File "/opt/gocd/gomatic/go_cd_configurator.py", line 432, in save_updated_config
    config_after = prettify(self.config)
  File "/opt/gocd/gomatic/go_cd_configurator.py", line 74, in config
    self.reorder_elements_to_please_go()
  File "/opt/gocd/gomatic/go_cd_configurator.py", line 68, in reorder_elements_to_please_go
    pipeline.reorder_elements_to_please_go()
  File "/opt/gocd/gomatic/gocd/pipelines.py", line 530, in reorder_elements_to_please_go
    materials = self.materials
  File "/opt/gocd/gomatic/gocd/pipelines.py", line 397, in materials
    return [Materials(element) for element in elements]
  File "/opt/gocd/gomatic/gocd/materials.py", line 21, in Materials
    raise RuntimeError("don't know of material matching " + ET.tostring(element, 'utf-8'))
RuntimeError: don't know of material matching <svn dest="project_name" encryptedPassword="123456abc=" materialName="project_name" url="http://svn.example.com/svn/project_name/trunk" username="user" />

**Comment by hanej** [comment]
Is there any update on this issue?

**Comment by Drakekin** [comment]
I'm afraid there are no plans to add any new functionality to gomatic that aren't needed internally, as we do not have the resources to dedicate to this project at current.

**Comment by dudadornelles** [comment]
@hanej we would welcome a PR on this!
